server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO

spring:
  security:
    oauth2:
      client:
        registration:
          web-app-client-oidc:
            provider: spring
            client-id: web-app-client
            client-secret: 123456
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8080/login/oauth2/code/{registrationId}"
            scope: openid
            client-name: web-app-client-oidc
          web-app-client-authorization-code:
            provider: spring
            client-id: web-app-client
            client-secret: 123456
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8080/authorized"
            scope: customers.read
            client-name: web-app-client-authorization-code
        provider:
          spring:
            issuer-uri: http://localhost:9000
